name: Build and Test Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t site_analyzer -f front_end/Dockerfile .
    - name: Run tests on the Docker image
      run: docker run site_analyzer python front_end/test.py
